[package]
name = "marvin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-sc2 = { git = "https://github.com/UltraMachine/rust-sc2" }

[features]
wine_sc2 = ["rust-sc2/wine_sc2"]
